### PR TITLE
caaq functions placeholders

### PR DESCRIPTION
**Pull request by steffilazerte**
Initial pull for caaq functions

### CODE REVIEW

**Comment by ateucher** [comment]
So this now failing while building the vignette - it dies while trying to read the stations list from the air data ftp site [here](https://github.com/bcgov/rcaaqs/blob/2c8a28f6e60574f8de492ff69ffe1a271f3f3724/doc/rcaaqs.Rmd#L225-L227)... because [Travis doesn't like to talk to ftp servers](https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci).

I don't think any of those solutions are feasible here, so if we want this to work we will need to access the file some other way. The easiest would be to include the file in the package... thoughts @stephhazlitt @steffilazerte?

**Comment by steffilazerte** [comment]
I would include the file in the package, either in whole or in part, as a dedicated example file. It can also be used to run tests/examples and the vignette will still be relevant even if the online file disappears or gets moved. 
However, having said all this, I'm not sure how large that file is :)

**Comment by ateucher** [comment]
That makes total sense to me - and the file is only 60kb.

**Comment by stephhazlitt** [comment]
I would include a smaller version of that source file, maybe where the wrangling steps required in the vignette are fewer. And somewhere we should add the documentation re: the source (i.e. from the B.C. Data Catalogue, OGL-British Columbia, go there for more up-to-date version)?

**Comment by ateucher** [comment]
Yep, I did the latter (at least partly), but not yet the former: https://github.com/bcgov/rcaaqs/pull/31/commits/3d751cedc50d0262b84ec19ed29d497339c18203.

Passing on Travis now!

**Pull request merged**
